      *****************************************************************
      *                                                               *
      * NAME = BAQAUTH                                                *
      *                                                               *
      * DESCRIPTIVE NAME = COBOL sample program to call restful       *
      *                    API protected by OAuth2.0 using            *
      *                    z/OS Connect EE API requester              *
      *****************************************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HWORLD.
       DATA DIVISION.
       WORKING-STORAGE SECTION.

      * Copy API Requester required copybook
       COPY BAQRINFO.

      *----------------------------------------------------------------*
      * API Request and Response,need to be replaced for each operation
      *----------------------------------------------------------------*


      * Copy request and response copybooks. These copybooks are
      * generated by build toolkit and used to describe the structure
      * of request and response.
      * This procedure is general and necessary.
      *
      * The request has eight fields to describe the model,
      * source language, target language and text needed to be
      * translated in translation program.
      *
      *   06 model-id-num                  PIC S9(9) COMP-5 SYNC.
      *
      *   06 model-id.
      *       09 model-id2-length          PIC S9999 COMP-5 SYNC.
      *       09 model-id2                 PIC X(255).
      *
      *   06 Xsource-num                   PIC S9(9) COMP-5 SYNC.
      *
      *   06 Xsource.
      *       09 Xsource2-length           PIC S9999 COMP-5 SYNC.
      *       09 Xsource2                  PIC X(255).
      *
      *    06 target-num                   PIC S9(9) COMP-5 SYNC.
      *
      *    06 target.
      *       09 target2-length            PIC S9999 COMP-5 SYNC.
      *       09 target2                   PIC X(255).
      *
      *    06 Xtext-num                    PIC S9(9) COMP-5 SYNC.
      *
      *    06 Xtext OCCURS 255.
      *       09 Xtext2-length             PIC S9999 COMP-5 SYNC.
      *       09 Xtext2                    PIC X(255).
      *       09 filler                    PIC X(1).
      *
      * The response has four fields to describe text after translation,
      * number of words and characters in translated text.
      * They will be filled up with information of the requested book.
      *    06 word-count                   PIC S9(18) COMP-5 SYNC.
      *    06 character-count              PIC S9(18) COMP-5 SYNC.
      *
      *    06 translations2-num            PIC S9(9) COMP-5 SYNC.
      *
      *    06 translations OCCURS 255.
      *        09 translation-length       PIC S9999 COMP-5 SYNC.
      *        09 translation              PIC X(255).
      *        09 filler                   PIC X(1).
      *
       01  REQUEST.
           COPY JMT00Q01.
       01  RESPONSE PIC X(255).
      *     COPY JMT00P01.
       01  API-INFO-API1.
           COPY JMT00I01.

      * Request and Response segment, used to store request and
      * response content.
       01 BAQ-REQUEST-PTR             USAGE POINTER.
       01 BAQ-REQUEST-LEN             PIC S9(9) COMP-5 SYNC.
       01 BAQ-RESPONSE-PTR            USAGE POINTER.
       01 BAQ-RESPONSE-LEN            PIC S9(9) COMP-5 SYNC.
       77 COMM-STUB-PGM-NAME          PIC X(8) VALUE 'BAQCSTUB'.

      * oAuth parameter.
       01 BAQ-OAUTH-SCOPE             PIC X(255).

       LINKAGE SECTION.

      *----------------------------------------------------------------*
      * Procedures
      *----------------------------------------------------------------*
       PROCEDURE DIVISION.
       MAINLINE SECTION.

           INITIALIZE REQUEST.
           INITIALIZE RESPONSE.

      * Use pointer and length to specify the location of
      *  request and response segment.
      * This procedure is general and necessary.
           SET BAQ-REQUEST-PTR TO ADDRESS OF REQUEST.
           MOVE LENGTH OF REQUEST TO BAQ-REQUEST-LEN.
           SET BAQ-RESPONSE-PTR TO ADDRESS OF RESPONSE.
           MOVE LENGTH OF RESPONSE TO BAQ-RESPONSE-LEN.

      * Segun Alberto dado el nombre me debiera devolver Hello <nombre>
           MOVE 'RAFAEL' TO name.
           MOVE 6 TO name-length

      * Client ID and client secrete are used for the authorization
      * server to authenticate the client credentials.
           MOVE "d18d537f-6d32-4620-b188-56bba0ab9d54"
           TO BAQ-OAUTH-CLIENTID.
           MOVE 36 TO BAQ-OAUTH-CLIENTID-LEN.

      *   MOVE "12345678901234567890123456789012345678901234567890"
           MOVE "Y5yO8vG6hF3wY2qY1uX2uO4wS8vN8wL6cS1wB8kQ1pY8oN5rO2"
               TO BAQ-OAUTH-CLIENT-SECRET.
           MOVE 40 TO BAQ-OAUTH-CLIENT-SECRET-LEN.

           MOVE 36 TO  X-IBM-Client-Id-length
           MOVE 'd18d537f-6d32-4620-b188-56bba0ab9d54'
               TO  X-IBM-Client-Id.

      * Scope is used to indicate the access permissions
      * granted to the client.
           MOVE "scope1" TO BAQ-OAUTH-SCOPE.
           SET BAQ-OAUTH-SCOPE-PTR TO ADDRESS OF BAQ-OAUTH-SCOPE.
           MOVE 6 TO BAQ-OAUTH-SCOPE-LEN.

      * Call BAQCSTUB, pass parameters, and receive result.
      * This procedure is necessary.
           CALL COMM-STUB-PGM-NAME USING
                           BY REFERENCE   API-INFO-API1
                           BY REFERENCE   BAQ-REQUEST-INFO
                           BY REFERENCE   BAQ-REQUEST-PTR
                           BY REFERENCE   BAQ-REQUEST-LEN
                           BY REFERENCE   BAQ-RESPONSE-INFO
                           BY REFERENCE   BAQ-RESPONSE-PTR
                           BY REFERENCE   BAQ-RESPONSE-LEN.

      * The BAQ-RETURN-CODE field in 'BAQRINFO' indicates whether this
      * API call is successful.

      * When BAQ-RETURN-CODE is 'BAQ-SUCCESS', response is
      * successfully returned and fields in RESPONSE copybook
      * can be obtained. Display the translation result.
           IF BAQ-SUCCESS THEN
              DISPLAY "CADENA: " RESPONSE

      * Otherwise, some error happened in API, z/OS Connect EE server
      * or communication stub. 'BAQ-STATUS-CODE' and
      * 'BAQ-STATUS-MESSAGE' contain the detailed information
      *  of this error.
           ELSE
              EVALUATE TRUE
      * When error happens in API, BAQ-RETURN-CODE is BAQ-ERROR-IN-API.
      * BAQ-STATUS-CODE is the HTTP response code of API.
                 WHEN BAQ-ERROR-IN-API
                   DISPLAY "API RETURN ERROR: " BAQ-STATUS-CODE
                   DISPLAY "API RETURN ERROR MESSAGE: "
                                             BAQ-STATUS-MESSAGE
      * When error happens in server, BAQ-RETURN-CODE is
      * BAQ-ERROR-IN-ZCEE
      * BAQ-STATUS-CODE is the HTTP response code of
      * z/OS Connect EE server.
                 WHEN BAQ-ERROR-IN-ZCEE
                   DISPLAY "SERVER RETURN ERROR: " BAQ-STATUS-CODE
                   DISPLAY "SERVER RETURN ERROR MESSAGE: "
                                            BAQ-STATUS-MESSAGE
      * When error happens in communication stub, BAQ-RETURN-CODE is
      * BAQ-ERROR-IN-STUB, BAQ-STATUS-CODE is the error code of STUB.
                 WHEN BAQ-ERROR-IN-STUB
                   DISPLAY "STUB RETURN ERROR: " BAQ-STATUS-CODE
                   DISPLAY "STUB RETURN ERROR MESSAGE: "
                                            BAQ-STATUS-MESSAGE
              END-EVALUATE
           END-IF.

           STOP RUN.
       END PROGRAM HWORLD.